#! /bin/sh
# /etc/init.d/sin_agent: start the sin_agent daemon.

# chkconfig: 345 90 10
# description: sin_agent

HOME=/home/liwang/GITROOT/sin
USER=root
NODE_ID=0

export JAVA_HOME=/export/apps/jdk/JDK-1_6_0_21

export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:$JAVA_HOME/bin

prog=sin_agent
DESC="sin_agent daemon"

RETVAL=0

# detect the distribution:
if [ -f /etc/redhat-release -o -f /etc/fedora-release ] ; then
  DISTRIBUTION="redhat"
elif [ -f /etc/SuSE-release ] ; then
  DISTRIBUTION="suse"
elif [ -f /etc/debian_version ] ; then
  DISTRIBUTION="debian"
else
  DISTRIBUTION="debian"
fi

# Source function library.
[ "$DISTRIBUTION" = "redhat" ] && . /etc/init.d/functions
[ "$DISTRIBUTION" = "suse" ] && . /etc/rc.status

if [ "$DISTRIBUTION" = "suse" ] ; then
  echo_success() {
    rc_status -v
  }
  echo_failure() {
    rc_status -v
  }
  success() {
    echo_success
  }
  failure() {
    echo_success
  }
elif [ "$DISTRIBUTION" = "debian" ] ; then
  echo_success() {
    echo ok
  }
  echo_failure() {
    echo failed
  }
  success() {
    echo_success
  }
  failure() {
    echo_success
  }
fi

start() {
  ulimit -n 65536
  ulimit -s 10240
  ulimit -c unlimited
  echo -n $"Starting $prog: "
  nohup su $USER -c $"python $HOME/app/agent/sin_agent.py $NODE_ID </dev/null 2>&1 | cronolog $HOME/log/sin_agent/sin_agent.%Y%m%d.log 2>&1" </dev/null >/dev/null 2>&1 &
  RETVAL=$?
  [ $RETVAL -eq 0 ] && echo_success
  [ $RETVAL -ne 0 ] && echo_failure
    echo
  return $RETVAL
}

stop() {
  echo $"Stopping $prog: "
  for pid in `ps ax -o  "pid pgid args" | \grep "[p]ython $HOME/app/agent/sin_agent.py $NODE_ID$" | awk '{print $1}'`; do
    echo -n $"Stopping $prog($pid): "
    kill $pid
    RETVAL=$?
    c=3500
    while [ $c -gt 0 ]; do
      let c=$c-1
      flag=1
      for p in `ps ax -o  "pid pgid args" | \grep -E $"$pid +[0-9]+ +"`; do
        flag=0
        break
      done
      if [ $flag -ne 0 ]; then
        break
      fi
      sleep .1
    done
    if [ $c -le 0 ]; then
      RETVAL=1
    fi
  done
  [ $RETVAL -eq 0 ] && echo_success
  [ $RETVAL -ne 0 ] && echo_failure
    echo
  return $RETVAL
}

reload() {
  stop
  start
}

restart() {
  stop
  start
}

case "$1" in
start)
  start
  ;;

stop)
  stop
  ;;

reload)
  reload
  ;;

restart)
  restart
  ;;

*)
  echo $"Usage: $0 {start|stop|reload|restart}"
  exit 1
esac

exit $?

