#! /bin/sh
# /etc/init.d/zookeeper: start the zookeeper daemon.

# chkconfig: 345 70 30
# description: zookeeper

HOME=/home/liwang/apps/kafka
USER=root

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin

prog=zookeeper
DESC="zookeeper daemon"

RETVAL=0

# detect the distribution:
if [ -f /etc/redhat-release -o -f /etc/fedora-release ] ; then
  DISTRIBUTION="redhat"
elif [ -f /etc/SuSE-release ] ; then
  DISTRIBUTION="suse"
elif [ -f /etc/debian_version ] ; then
  DISTRIBUTION="debian"
else
  DISTRIBUTION="debian"
fi

# Source function library.
[ "$DISTRIBUTION" = "redhat" ] && . /etc/init.d/functions
[ "$DISTRIBUTION" = "suse" ] && . /etc/rc.status

if [ "$DISTRIBUTION" = "suse" ] ; then
  echo_success() {
    rc_status -v
  }
  echo_failure() {
    rc_status -v
  }
  success() {
    echo_success
  }
  failure() {
    echo_success
  }
elif [ "$DISTRIBUTION" = "debian" ] ; then
  echo_success() {
    echo ok
  }
  echo_failure() {
    echo failed
  }
  success() {
    echo_success
  }
  failure() {
    echo_success
  }
fi

start() {
  ulimit -n 65536
  ulimit -s 10240
  ulimit -c unlimited
  echo -n $"Starting $prog: "
  cd $HOME
  nohup su $USER -c "./bin/zookeeper-server-start.sh ./config/zookeeper.properties </dev/null 2>&1 | cronolog ./log/zookeeper/zookeeper.%Y%m%d.log 2>&1" </dev/null >/dev/null 2>&1 &
  RETVAL=$?
  [ $RETVAL -eq 0 ] && echo_success
  [ $RETVAL -ne 0 ] && echo_failure
    echo
  return $RETVAL
}

stop() {
  echo $"Stopping $prog: "
  for pgid in `ps ax -o  "pid pgid args" | \grep .[/]bin/zookeeper-server-start.sh | awk '{print $2}'`; do
    for pid in `ps ax -o  "pid pgid args" | \grep -E $"[0-9]+ +$pgid +" | \grep java | awk '{print $1}'`; do
      echo -n $"Stopping $prog($pid): "
      kill $pid
      RETVAL=$?
      c=50
      while [ $c -gt 0 ]; do
        let c=$c-1
        flag=1
        for p in `ps ax -o  "pid pgid args" | \grep -E $"[0-9]+ +$pgid +"`; do
          flag=0
          break
        done
        if [ $flag -ne 0 ]; then
          break
        fi
        sleep .1
      done
      if [ $c -le 0 ]; then
        RETVAL=1
      fi
    done
  done
  [ $RETVAL -eq 0 ] && echo_success
  [ $RETVAL -ne 0 ] && echo_failure
    echo
  return $RETVAL
}

reload() {
  stop
  start
}

restart() {
  stop
  start
}

case "$1" in
start)
  start
  ;;

stop)
  stop
  ;;

reload)
  reload
  ;;

restart)
  restart
  ;;

*)
  echo $"Usage: $0 {start|stop|reload|restart}"
  exit 1
esac

exit $?

